"""Leave Database

Revision ID: ea1b9f44c01d
Revises: 738c8710057a
Create Date: 2021-05-01 15:42:42.543967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1b9f44c01d'
down_revision = '738c8710057a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('roll_no', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('additional_comments', sa.String(length=100), nullable=True),
    sa.Column('logged_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('filename', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leave')
    # ### end Alembic commands ###
